Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Infrastructure.Models;
using Infrastructure.Service;
using System.Web.Helpers;

namespace Web.Controllers
{
    public class AdminController : Controller
    {
        private IUserService userService;

        public AdminController(IUserService userService)
        {
            this.userService = userService;
        }
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RegisterUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegisterUser(Users user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    userService.RegisterUser(user);
                }
            }
            catch
            {
                Response.StatusCode = 500;
            }

                return View();
        }

        public ActionResult DisplayUsers()
        {
           IEnumerable<Users> allUsers = userService.GetAllUsers();
           return View(allUsers);
        }

        public void DeleteUser(int Id)
        {
            try 
            {
                userService.DeleteUser(Id);
                
            }
            catch 
            {
                Response.StatusCode = 500;
            }
           
           
        }

    }
}

Web/Controllers/HomeController.cs
using Infrastructure.Models;
using Infrastructure.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private IUserService userService;

        public HomeController(IUserService userService)
        {
            this.userService = userService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login([Bind(Include = "UserName,Password")] Users user)
        {
            if (this.userService.VerifyUser(user))
            {
                TempData["Message"] = "Success";
            }
            else
            {
                TempData["Message"] = "Failure";
            }

            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

    }
}

Web/Views/Admin/DisplayUsers.cshtml
@using Users = Infrastructure.Models.Users
@model IEnumerable<Users>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

        <script type="text/javascript">
        $('.delete-link').click(function () {
            var Id = $(this).attr('id');
            $result = deleteRecord(Id);
            if ($result == '1') {
                $(this).parent().parent().remove();
                alert('User Deleted Succssfully');
            }
            else {
                alert('Failure');
            }

        });
        function deleteRecord(id) {
            var result;
            $.ajax({
                type: "POST",
                url: "/Admin/DeleteUser",
                data: JSON.stringify({ Id: id }),
                async: false,
                contentType: "application/json; charset=utf-8",

                success: function () {
                    result = '1';
                },

                failure: function () {
                    alert("Failure to delete the Record!");
                    result = '0';
                }
            });
            return result;
        };
    </script>
}


@section featured
{
    <table id="users-records">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>UserName</th>
            <th>Email</th>
        </tr>
        @{
            foreach (var user in Model)
            {
                <tr>
                    <td>@user.FirstName</td>
                    <td>@user.LastName</td>
                    <td>@user.UserName</td>
                    <td>@user.Email</td>
                    <td><a href="#" class="delete-link" id="@user.Id">Delete</a></td>

                </tr>
            }
        }
    </table>
} 

Web/Views/Admin/RegisterUser.cshtml
@model Infrastructure.Models.Users

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm("RegisterUser", "Admin", FormMethod.Post))
{
<table>
    
    <tr>
        <td>@Html.LabelFor(x=>x.FirstName)</td>
        <td>@Html.TextBoxFor(x=>x.FirstName)</td>
    </tr>

    <tr>
        <td>@Html.LabelFor(x=>x.LastName)</td>
        <td>@Html.TextBoxFor(x=>x.LastName)</td>
    </tr>
     <tr>
        <td>@Html.LabelFor(x=>x.UserName)</td>
        <td>@Html.TextBoxFor(x=>x.UserName)</td>
    </tr>
    <tr>
        <td>@Html.LabelFor(x=>x.Password)</td>
        <td>@Html.PasswordFor(x=>x.Password)</td>
    </tr>
    <tr>
        <td>Confirm Password</td>
        <td>@Html.Password("ConfirmPassword")</td>
    </tr>
    <tr>
        <td>@Html.LabelFor(x=>x.Email)</td>
        <td>@Html.TextBoxFor(x=>x.Email)</td>
    </tr>

    <tr>
        <td></td>
        <td><input type="submit" value="Register" /></td>
    </tr>
</table>
}

Web/Views/Home/Login.cshtml
@model Infrastructure.Models.Users

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>



@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{
    <table>

        <tr>
            <td>@Html.LabelFor(x => x.UserName)</td>
            <td>@Html.TextBoxFor(x => x.UserName)</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(x => x.Password)</td>
            <td>@Html.PasswordFor(x => x.Password)  @TempData["Message"] </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <input type="submit" value="Login" />
            </td>
        </tr>
    </table>
}

Web/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <link href="~/Styles/Layout.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-1.8.2.js"></script>


</head>
<body>
    <div id="header">
        <h1>Suppliers Portal </h1>
    </div>

    <div id="nav">

    </div>

    <div id="body">
        @RenderSection("featured", required: false)
        <section id="section">
            @RenderBody()
        </section>
    </div>

    <div id="footer">

    </div>
</body>
</html>